---
title: title
date: 2021-02-20
---
author: Jeff
email: sth@qq.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. It's always a good time.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
